### ISSUE TITLE
Porting to ESP32

### ISSUE THREAD

**Issue by danpshyco** [Tom-evnut/BMWPhevBMS#1]
Hello Tom.It is possible to port the scketch from teense to esp32 board? Teense right now it,s very hard to find.Thanks!

**Comment by Tom-evnut** [comment]
Anything is possible depending on your coding skills. All that needs changing is  the Can and inputs outputs.

**Comment by danpshyco** [comment]
I.am not so good to do this.....I  can.t understand very well Can protocol and speed communication, using Can FD into esp32 it.s not compatibile.If u want to help me with this...Ok othewise I must use another type of Bms fot the batterys.Thanks very much for everithink!
